rooms/urls.py
from django.urls import path

from .views import (
    list_rooms,
    view_room,
    create_room,
    delete_room,
    update_room
)

urlpatterns = [
    path('', list_rooms, name='list-rooms'),
    path('create/', create_room, name='create-room'),
    path('<int:id>/', view_room, name='view-room'),
    path('<int:id>/edit/', update_room, name='update-room'),
    path('<int:id>/delete/', delete_room, name='delete-room'),
]

studyroom/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
        home,
        show_profile,
        update_profile,
        register_view,
        login_view,
        logout_view
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/', include('rooms.urls')),
    path('', home, name='home'),
    path('profile/<int:id>', show_profile, name='show-profile'),
    path('profile/edit', update_profile, name='update-profile'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

rooms/models.py
from unicodedata import name
from django.db import models
from django.conf import settings
from django.db.models import Q

from topics.models import Topic

User = settings.AUTH_USER_MODEL

# Create your models here.
class RoomQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.none()
        lookups = (
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(topic__name__icontains=query)
        )
        return self.filter(lookups) 

class RoomManager(models.Manager):
    def get_queryset(self):
        return RoomQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = RoomManager()

    def __str__(self):
        return self.name

templates/components/activities_sidebar.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>

    {% for message in messages %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'show-profile' id=message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="https://randomuser.me/api/portraits/women/11.jpg" />
          </div>
          <p>
            @{{ message.user.username }}
            <span>{{ message.created_at|timesince }} ago</span>
          </p>
        </a>
        <div class="roomListRoom__actions">
          <a href="#">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'view-room' id=message.room.id %}">{{ message.room.name }}</a>”</p>
        <div class="activities__boxRoomContent">
          {{ message.body|slice:50 }} ...
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

templates/components/topics_sidebar.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home' %}" class="active">All <span>{{ topics.count }}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{% url 'list-rooms' %}?q={{ topic.name }}">{{ topic.name }} <span>{{ topic.room_set.count }}</span></a>
      </li>
      {% endfor %}
    </ul>
    <a class="btn btn--link" href="topics.html">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>